### ISSUE TITLE
How to separate the two projects (Angular & express)

### ISSUE THREAD

**Issue by elmoromourad** [jakblak/chat_app#1]
Hello, 
First of all, that's not an issue.
However, I want just to know how to separate server side to client side. In other way, how can I run the two projects (angular project and express project) into two differents servers.
That's gonna help me to use this code also into ionic framework :)

**Comment by jakblak** [comment]
I'm not sure about the details on this but you would have CORS enabled on both would be key.

Then you might have a simple server setup for the client stuff that connects to the server with endpoints.  And the code for the controllers, models, etc. go in the other server.js file.
